support/scripts: Fix gdb helper script
The gdb helper script has two issues:

1. `uk-gdb.py` cannot import uk_trace, causing
   ModuleNotFoundError: No module named 'uk_trace'

2. String value is treated as integer, when a `pickle` format file
   (which is saved via `uk trace save` in GDB helper script) is loaded:
   `parse.py` uses `elf` in a `%d` formatting operation
   This causes the parser to fail with:
   TypeError: %d format: a real number is required, not str

Move import uk_trace after appending the script dir to sys.path.

The ELF path is not used after loading, so remove it from the pickle dump.

Signed-off-by: Gyunseo Lee <gyunseo.lee@boeing.com>
Signed-off-by: Anderson Choi <anderson.choi@boeing.com>